### ISSUE TITLE
Need more examples

### ISSUE THREAD

**Issue by cawa-93** [oscartbeaumont/spectroscope#21]
Today I tried to integrate  spectroscope into my template ([vite-electron-builder](https://github.com/cawa-93/vite-electron-builder)). Unfortunately, I was unable to do so.
Some things I did not understand:
- How to integrate this with ESM?
- Is there support for TypeScript?
- How to configure the bundler so as not to include the spectroscope in the production bundle?

I've tried a few combinations, but whatever I do I get the error `Spectroscope not injected into Electron preload context!`

**Comment by oscartbeaumont** [comment]
Typescript should be working as of version v2.0.2 (I just released this version so update your project). Theoretically, ESM is supported but I have a limited knowledge on that part of the JS ecosystem so I have not been able to test it.

To fix the preload context issue. Ensure your application has devtools disabled when running the test suite and ensure a preload script exists that contains the code `require("spectroscope/preload");`. Even if your using Typescript you should be able to copy directly from the example project (using the `require` syntax). If this still doesn't work, can you get the example project working on your machine? Check out the Wiki for help doing this.

To allow Spectroscope to be excluded from the production bundle you must add it as a devDependencies and also configure your code to not `require` Spectroscope in production as it won't exist. This could be done in Vite using a snippet like:
```js
// Note: I have not tested this but it should work
if (import.meta.env.MODE === 'test') {
    // Require Statement.
}
```
This if statement would wrap the Spectroscope import statement for the preload script (`require("spectroscope/preload");`) and the main script (`require("spectroscope/main");`). I will try and add some more documentation for this.

I am developing Spectroscope as I develop an Electron app so the entire project although functional definitely has heaps of room for improvement and will be over the coming months.

**Comment by cawa-93** [comment]
Thank you for your time. This question is no longer relevant to me, because the team decided to migrate to the [playwright](https://playwright.dev/). One strong argument was that it could be used without interfering directly with the code base. I hope it will be useful for you.
